version: "3.7"

networks:
  airflow:

x-dags-and-logs: &dags-and-logs
  - ./dags:/opt/airflow/dags
  - ./logs:/opt/airflow/logs
  - ./files:/opt/airflow/files
  - ./airflow-tutorial:/home/airflow/airflow-tutorial
  - ./maintenance:/home/airflow/maintenance

x-airflow-env:
  &dags-folder-env
  - DAG_FOLDERS=/home/airflow/airflow-tutorial,/home/airflow/maintenance


services:
  db:
    image: postgres:13.1
    container_name: airflow-db
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - 5432:5432
    volumes:
      - ./database/pg-data:/var/lib/postgresql/data
    networks:
      - airflow

  redis:
    image: redis:6.0.9
    container_name: airflow-redis
    ports:
      - 6379:6379
    networks:
      - airflow

  webserver:
    image: apache/airflow:2.0.0-python3.8
    container_name: airflow-webserver
    environment:
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
    env_file:
      - .env
    volumes:
      *dags-and-logs
    ports:
      - 8080:8080
    depends_on:
      - db_upgrade
    command: webserver
    networks:
      - airflow

  scheduler:
    image: apache/airflow:2.0.0-python3.8
    container_name: airflow-scheduler
    environment:
      *dags-folder-env
    env_file:
      - .env
    volumes:
      *dags-and-logs
    depends_on:
      - webserver
    command: scheduler
    networks:
      - airflow

  worker:
    image: apache/airflow:2.0.0-python3.8
    container_name: airflow-worker
    environment:
      - AIRFLOW__WEBSERVER__BASE_URL=http://airflow.mydomain.com:8080
    env_file:
      - .env
    volumes:
      *dags-and-logs
    depends_on:
      - db
    command: celery worker
    networks:
      - airflow

  pgadmin:
    image: dpage/pgadmin4:4.29
    container_name: airflow-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 8082:80
    depends_on:
      - db
    networks:
      - airflow

  flower:
    image: apache/airflow:2.0.0-python3.8
    container_name: airflow-flower
    env_file:
      - .env
    volumes:
      *dags-and-logs
    ports:
      - 5555:5555
    depends_on:
      - redis
    command: celery flower
    networks:
      - airflow

  db_upgrade:
    image: apache/airflow:2.0.0-python3.8
    container_name: airflow-db-upgrade
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: db upgrade
    networks:
      - airflow

#  initdb:
#    image: apache/airflow:2.0.0-python3.8
#    container_name: airflow-initdb
#    env_file:
#      - .env
#    entrypoint: /bin/bash
#    command: -c "airflow db init && airflow users create --firstname Jose --lastname Assis --email admin --password admin --username admin --role Admin"
#    depends_on:
#      - redis
#      - db
#    networks:
#      - airflow
